import * as React from 'react';
import Timeline from '@mui/lab/Timeline';
import TimelineItem from '@mui/lab/TimelineItem';
import TimelineSeparator from '@mui/lab/TimelineSeparator';
import TimelineConnector from '@mui/lab/TimelineConnector';
import TimelineContent from '@mui/lab/TimelineContent';
import TimelineDot from '@mui/lab/TimelineDot';
import TimelineOppositeContent from '@mui/lab/TimelineOppositeContent';

import "./Timeline.scss";

function TimelineProfessional(){
    const cinereous = "rgba(147, 130, 127, 1)";
    const sage = "rgba(189, 196, 167, 1)";
    const jobs = [
        {
            date: "Aug. 2022 - Oct. 2022",
            title: "Junior Security Researcher, Bitdefender",
            subtitle: "Internship",
            description: [
                "gained a fundamental understanding of Networking and Pentesting;",
                "researched the area of cloud computing: OS Virtualization with Docker, orchestrating containers with Kubernetes;",
                "built a tool to detect Kubernetes attacks involving: container deployments, container command abuse, image implanting, by looking at the logs generated by the Kubernetes cluster."
            ]
        }, 
        {
            date: "July 2023 - Oct. 2023",
            title: "Python Developer, Orange Services",
            subtitle: "Internship",
            description: [
                "developed a producer-consumer architecture in Python, using RabbitMQ, for fast crawling and parsing social media chat messages, respectively shared files",
                "built a database that will be multi-threaded and populated with crawling information",
                "deployed the crawling architecture completely on Docker"
            ],
        },{
            date: "Oct. 2023 - Present",
            title: "Python Developer, Orange Services",
            subtitle: "Part time",
            description: [
                "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi, sed.",
                "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi, sed.",
                "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sequi, sed."
            ],
        }
    ]

    const renderJobs = jobs.map(job => 
        <TimelineItem>
            <TimelineOppositeContent> 
                <h2 className='timeline-date__title'>{job.date}</h2>
            </TimelineOppositeContent>
            
            <TimelineSeparator>
                <TimelineDot sx={{ bgcolor: cinereous }}/>
                <TimelineConnector sx={{ bgcolor: sage }}/>
            </TimelineSeparator>
            
            <TimelineContent>
                <h2 className='timeline-job__title'>{job.title}</h2>
                <h5 className='timeline-job__subtitle'>{job.subtitle}</h5>
                <div className="timeline-job__description timeline-job__description-professional">
                    {
                        job.description.map(description => 
                            <div>
                                <p>⭐ {description}</p>
                                <br></br>
                            </div>
                        )
                    }
                </div>
            </TimelineContent>
        </TimelineItem>
    );

    return (
        <div className='timeline__wrapper timeline__academical'>
            <div className="timeline__type">
                P<br/>
                R<br/>
                O<br/>
                F<br/>
                E<br/>
                S<br/>
                S<br/>
                I<br/>
                O<br/>
                N<br/>
                A<br/>
                L
            </div>  
            <div className="timeline__display">
                <Timeline>
                    {renderJobs}
                </Timeline>
            </div>
        </div>
    );
}

export default TimelineProfessional;